### ISSUE TITLE
'type' object has no attribute 'BuildPath'

### ISSUE THREAD

**Issue by gfrhj** [squidgy617/BrawlInstallerPlugins#7]
After doing the setup and then choosing "Install Character" I get this pop up. 
![image](https://user-images.githubusercontent.com/57181282/185921954-09c9f15a-411b-45c9-ad50-8431b20c827f.png)

**Comment by squidgy617** [comment]
This is most likely because you need to switch to BrawlCrate Canary.

Per the readme:
Open BrawlCrate and navigate to Tools > Settings > Updater, then check the "Opt into BrawlCrate Canary (Experimental) updates" box. You should also ensure you have your build path set to your build's root folder by navigating to Tools > Settings > General and modifying the "Default Build Path" there.

Let me know if it still doesn't work after you update and restart.
